// Meaningful color system based on session status and progress
export const getSessionCardColor = (completionPercentage, status) => {
  // Completed sessions - celebratory green
  if (completionPercentage === 100 || status === 'Completed') {
    return { bgcolor: 'linear-gradient(135deg, #e6f8f3 0%, #f0fdf4 100%)', meaning: 'Completed' };
  }
  
  // High progress sessions (70%+) - encouraging blue
  if (completionPercentage >= 70) {
    return { bgcolor: 'linear-gradient(135deg, #eaf7ff 0%, #f0f9ff 100%)', meaning: 'High Progress' };
  }
  
  // Medium progress sessions (30-69%) - motivating purple
  if (completionPercentage >= 30) {
    return { bgcolor: 'linear-gradient(135deg, #f0ecff 0%, #f5f3ff 100%)', meaning: 'In Progress' };
  }
  
  // Low progress sessions (1-29%) - gentle orange
  if (completionPercentage > 0) {
    return { bgcolor: 'linear-gradient(135deg, #fff2e9 0%, #fff7ed 100%)', meaning: 'Getting Started' };
  }
  
  // New/untouched sessions - neutral gray
  return { bgcolor: 'linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)', meaning: 'Ready to Start' };
};

// Legacy CARD_BG for backward compatibility (now unused)
export const CARD_BG = [
  { id: 1, bgcolor: 'linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)' },
  { id: 2, bgcolor: 'linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)' },
  { id: 3, bgcolor: 'linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)' },
  { id: 4, bgcolor: 'linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)' },
  { id: 5, bgcolor: 'linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)' },
  { id: 6, bgcolor: 'linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)' },
  { id: 7, bgcolor: 'linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)' },
  { id: 8, bgcolor: 'linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)' },
  { id: 9, bgcolor: 'linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)' },
  { id: 10, bgcolor: 'linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%)' },
];

export const APP_FEATURES = [
  {
    id: "01",
    title: "Tailored Just for You",
    description:
      "Get interview questions and model answers based on your role, experience, and specific focus areas - no...",
  },
  {
    id: "02",
    title: "Learn at Your Own Pace",
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed explanations.",
  },
  {
    id: "03",
    title: "Capture Your Insights",
    description:
      "Add personal notes to any question and pin important ones to the top - making your learning more organized.",
  },
  {
    id: "04",
    title: "Understand the \"Why\" Behind Answers",
    description:
      "Beyond just answers - unlock detailed concept explanations generated by AI, helping you truly master each concept.",
  },
  {
    id: "05",
    title: "Save, Organize, and Revisit",
    description:
      "Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation right where you left off.",
  },
];